/*---------------------------------------------------------------------------------------------
 *  Log Statistics Manager
 *  Unified management of statistics query, calculation, and persistence
 *  Directory structure:
 *    - Statistics summary: <baseDir>/usages/YYYY-MM-DD/stats.json
 *     Contains daily (daily statistics) and hourly (hourly statistics) parts
 *    - Date index: <baseDir>/usages/index.json
 *     Records total token usage for all dates for quick date list browsing
 *--------------------------------------------------------------------------------------------*/

import * as fs from 'fs/promises';
import * as fsSync from 'fs';
import * as path from 'path';
import { StatusLogger } from '../../utils/statusLogger';
import { LogReadManager } from './logReadManager';
import { LogIndexManager } from './logIndexManager';
import { StatsCalculator } from './statsCalculator';
import { AtomicJsonFile } from '../atomicJsonFile';
import type {
    FileLoggerModelStats,
    FileLoggerProviderStats,
    HourlyStats,
    TokenStats,
    TokenUsageStatsFromFile
} from './types';

/**
 * Log Statistics Manager
 * Unified management of statistics query, calculation, and persistence
 * Note: Cache is maintained by upper-level callers (usagesStatusBar, etc.)
 */
export class LogStatsManager {
    private readonly baseDir: string;
    private readonly indexManager: LogIndexManager;
    private readonly inFlightRegenerations = new Map<string, Promise<TokenUsageStatsFromFile>>();
    // Cache creation timestamp: used to determine if cache is newer than log file
    private _cacheVersionTimestamp: number = 0;
    // Code version timestamp: used to determine if cache was generated by current version code
    private _codeVersionTimestamp: number = 0;

    constructor(
        private readManager: LogReadManager,
        baseDir: string,
        indexManager: LogIndexManager
    ) {
        this.baseDir = path.join(baseDir, 'usages');
        this.indexManager = indexManager;
    }

    /**
     * Update cache version timestamp
     * @param cacheTimestamp Cache creation timestamp
     * @param codeVersionTimestamp Code version timestamp
     */
    updateCacheVersionTimestamp(cacheTimestamp: number, codeVersionTimestamp: number): void {
        this._cacheVersionTimestamp = cacheTimestamp;
        this._codeVersionTimestamp = codeVersionTimestamp;
    }

    /**
     * Get current cache creation timestamp
     */
    private getCacheVersionTimestamp(): number {
        return this._cacheVersionTimestamp;
    }

    /**
     * Get current code version timestamp
     */
    private getCodeVersionTimestamp(): number {
        return this._codeVersionTimestamp;
    }

    /**
     * Get date statistics
     * First try reading from persisted file, otherwise perform full calculation and save
     * If version timestamp changes or cache expires, perform full recalculation
     * @param dateStr Date string (YYYY-MM-DD)
     * @param ignoreCache Whether to ignore cache and force recalculation
     */
    async getDateStats(dateStr: string, ignoreCache: boolean = false): Promise<TokenUsageStatsFromFile> {
        // First try reading from persisted file (if not ignoring cache)
        if (!ignoreCache) {
            const saved = await this.loadStats(dateStr);
            if (saved) {
                // Check if version timestamp is valid, if invalid need full recalculation
                const needsRegen = await this.needsRegeneration(dateStr);
                if (!needsRegen) {
                    StatusLogger.debug(`[LogStatsManager] Read statistics from cache: ${dateStr}`);
                    return saved;
                }
                // Version changed or cache expired, need full recalculation
                StatusLogger.debug(`[LogStatsManager] Cache expired, full recalculation: ${dateStr}`);
            }
        }

        return this.getOrCreateDateRegeneration(dateStr);
    }

    /**
     * Get or create recalculation task for specified date
     * Avoid old snapshot overwriting new snapshot when multiple callers concurrently recalculate on the same day
     */
    private getOrCreateDateRegeneration(dateStr: string): Promise<TokenUsageStatsFromFile> {
        const inFlight = this.inFlightRegenerations.get(dateStr);
        if (inFlight) {
            StatusLogger.trace(`[LogStatsManager] Reusing in-progress date statistics recalculation task: ${dateStr}`);
            return inFlight;
        }

        const regenerationPromise = (async () => {
            StatusLogger.debug(`[LogStatsManager] Incremental calculation of statistics: ${dateStr}`);
            const stats = await this.calculateDateStats(dateStr);
            await this.saveDateStats(dateStr, stats);
            return stats;
        })();

        const sharedPromise = regenerationPromise.finally(() => {
            if (this.inFlightRegenerations.get(dateStr) === sharedPromise) {
                this.inFlightRegenerations.delete(dateStr);
            }
        });

        this.inFlightRegenerations.set(dateStr, sharedPromise);
        return sharedPromise;
    }

    /**
     * Calculate statistics for specified date (includes hourly and date statistics)
     * Supports incremental updates: determine if recalculation is needed based on hour file modification timestamp
     * If version changes, skip old hourly cache and recalculate all
     * Date statistics (total and providers) are aggregated from hourly cache
     *
     * Calculation notes:
     * - `StatsCalculator.aggregateLogs()` is only responsible for calculating and writing "model-level" aggregated values:
     *   - `outputSpeeds`: Robust mean of model request speed within hour (used to avoid extreme values).
     *   - `firstTokenLatency`: Arithmetic mean of model first token latency within hour (no confidence/robust processing).
     * - This method, after "hourly cache" is ready, fills back hourly provider/hour and hour total aggregated values from models.
     * - Daily `outputSpeeds/firstTokenLatency` are both "arithmetic mean of hourly aggregated values" (mean of means, unweighted).
     * - `totalStreamDuration/validStreamRequests/...` and other intermediate counts are only used for runtime calculation (no longer written to cache).
     *
     * @private Internal use, accessed via getDateStats
     */
    private async calculateDateStats(dateStr: string): Promise<TokenUsageStatsFromFile> {
        // Read existing statistics
        const existingStats = await this.loadStats(dateStr);

        // Check if old cache should be skipped:
        // - No cache
        // - Cache has no versionTimestamp (old format)
        // - Cache version < current code version
        const hasValidCache =
            existingStats &&
            existingStats.versionTimestamp !== undefined &&
            existingStats.versionTimestamp >= this.getCodeVersionTimestamp();
        const existingHourly = hasValidCache ? existingStats.hourly || {} : {};
        if (!hasValidCache) {
            StatusLogger.debug(`[LogStatsManager] Invalid version, not using old cache, full recalculation: ${dateStr}`);
        }

        // Get all existing hour files in date folder
        const dateFolder = path.join(this.baseDir, dateStr);
        let hourFiles: number[] = [];
        try {
            const files = await fs.readdir(dateFolder);
            hourFiles = files
                .filter(f => f.endsWith('.jsonl'))
                .map(f => parseInt(f.slice(0, 2), 10))
                .filter(h => !Number.isNaN(h) && h >= 0 && h <= 23)
                .sort((a, b) => a - b);
        } catch {
            StatusLogger.debug(`[LogStatsManager] Date folder does not exist or cannot be read: ${dateStr}`);
        }

        // Initialize hourly statistics results
        const hourly: Record<string, HourlyStats> = { ...existingHourly };

        // Iterate through all hour files, incrementally update hourly cache
        for (const hour of hourFiles) {
            const hourKey = String(hour).padStart(2, '0');
            const hourFileModified = await this.readManager.getHourFileModifiedTime(dateStr, hour);
            const existingHourlyStats = existingHourly[hourKey];
            const existingModified = existingHourlyStats?.modifiedTime;

            // Check if recalculation is needed:
            // 1. If no existing statistics, need to calculate
            // 2. If file modification time changed, need to recalculate
            const needsRecalculate = !existingHourlyStats || existingModified !== hourFileModified;
            if (!needsRecalculate) {
                // File unchanged, keep existing statistics
                StatusLogger.trace(`[LogStatsManager] Hour file unchanged, skipping calculation: ${dateStr} ${hourKey}:00`);
                continue;
            }

            // Need to recalculate
            StatusLogger.debug(`[LogStatsManager] Hour file changed, recalculating: ${dateStr} ${hourKey}:00`);
            const logs = await this.readManager.readHourLogs(dateStr, hour);
            const hourStats = StatsCalculator.aggregateLogs(logs);
            // Update statistics for this hour (includes modifiedTime and providers)
            hourly[hourKey] = {
                ...hourStats.total,
                modifiedTime: hourFileModified,
                providers: hourStats.providers
            };
        }

        // After hourly cache is ready:
        // 1) First calculate hourly provider/hour and hour total aggregated values based on "hour+models"
        // 2) Then iterate through hours to calculate daily mean (mean of means, unweighted)
        interface AvgAcc {
            mean: number;
            n: number;
        }
        const addAvg = (acc: AvgAcc | undefined, value: number): AvgAcc => {
            const next = acc ?? { mean: 0, n: 0 };
            next.n += 1;
            next.mean += (value - next.mean) / next.n;
            return next;
        };
        const getAvg = (acc: AvgAcc | undefined): number => (acc && acc.n > 0 ? acc.mean : 0);

        // Aggregate date statistics from hourly statistics (avoid reading logs repeatedly)
        // Initialize totals
        const total: TokenStats = {
            estimatedInput: 0,
            actualInput: 0,
            cacheTokens: 0,
            outputTokens: 0,
            requests: 0,
            completedRequests: 0,
            failedRequests: 0,
            firstTokenLatency: 0,
            outputSpeeds: 0
        };

        let totalSpeedAcc: AvgAcc | undefined;
        let totalFirstTokenLatencyAcc: AvgAcc | undefined;

        // Initialize provider statistics
        const providers: Record<string, FileLoggerProviderStats> = {};
        const providerMetricAccByDay = new WeakMap<FileLoggerProviderStats, { speed?: AvgAcc; latency?: AvgAcc }>();
        const modelMetricAccByDay = new WeakMap<FileLoggerModelStats, { speed?: AvgAcc; latency?: AvgAcc }>();
        // Iterate through all hourly statistics, aggregate calculation
        for (const hourStats of Object.values(hourly)) {
            // 1) Fill back hourly provider/hour aggregated values: only calculate from models' aggregated values
            let hourTotalSpeedAcc: AvgAcc | undefined;
            let hourTotalLatencyAcc: AvgAcc | undefined;
            for (const providerStats of Object.values(hourStats.providers || {})) {
                let providerSpeedAcc: AvgAcc | undefined;
                let providerLatencyAcc: AvgAcc | undefined;
                for (const modelStats of Object.values(providerStats.models || {})) {
                    if (modelStats.firstTokenLatency && modelStats.firstTokenLatency > 0) {
                        providerLatencyAcc = addAvg(providerLatencyAcc, modelStats.firstTokenLatency);
                        hourTotalLatencyAcc = addAvg(hourTotalLatencyAcc, modelStats.firstTokenLatency);
                    }
                    if (modelStats.outputSpeeds && modelStats.outputSpeeds > 0) {
                        providerSpeedAcc = addAvg(providerSpeedAcc, modelStats.outputSpeeds);
                        hourTotalSpeedAcc = addAvg(hourTotalSpeedAcc, modelStats.outputSpeeds);
                    }
                }
                providerStats.firstTokenLatency = getAvg(providerLatencyAcc);
                providerStats.outputSpeeds = getAvg(providerSpeedAcc);
            }

            hourStats.firstTokenLatency = getAvg(hourTotalLatencyAcc);
            hourStats.outputSpeeds = getAvg(hourTotalSpeedAcc);

            // 2) tokens/requests still accumulate
            total.estimatedInput += hourStats.estimatedInput;
            total.actualInput += hourStats.actualInput;
            total.cacheTokens += hourStats.cacheTokens;
            total.outputTokens += hourStats.outputTokens;
            total.requests += hourStats.requests;
            total.completedRequests += hourStats.completedRequests;
            total.failedRequests += hourStats.failedRequests;

            // 3) daily total: arithmetic mean of hourly aggregated values (unweighted)
            if (hourStats.firstTokenLatency && hourStats.firstTokenLatency > 0) {
                totalFirstTokenLatencyAcc = addAvg(totalFirstTokenLatencyAcc, hourStats.firstTokenLatency);
            }
            if (hourStats.outputSpeeds && hourStats.outputSpeeds > 0) {
                totalSpeedAcc = addAvg(totalSpeedAcc, hourStats.outputSpeeds);
            }

            // 4) providers/models: accumulate tokens, and calculate mean of hourly aggregated values
            for (const [providerKey, providerHour] of Object.entries(hourStats.providers || {})) {
                if (!providers[providerKey]) {
                    providers[providerKey] = {
                        providerName: providerHour.providerName,
                        estimatedInput: 0,
                        actualInput: 0,
                        cacheTokens: 0,
                        outputTokens: 0,
                        requests: 0,
                        completedRequests: 0,
                        failedRequests: 0,
                        models: {}
                    };
                }

                const provider = providers[providerKey];
                provider.estimatedInput += providerHour.estimatedInput;
                provider.actualInput += providerHour.actualInput;
                provider.cacheTokens += providerHour.cacheTokens;
                provider.outputTokens += providerHour.outputTokens;
                provider.requests += providerHour.requests;
                provider.completedRequests += providerHour.completedRequests;
                provider.failedRequests += providerHour.failedRequests;

                const pAcc = providerMetricAccByDay.get(provider) ?? {};
                if (providerHour.firstTokenLatency && providerHour.firstTokenLatency > 0) {
                    pAcc.latency = addAvg(pAcc.latency, providerHour.firstTokenLatency);
                }
                if (providerHour.outputSpeeds && providerHour.outputSpeeds > 0) {
                    pAcc.speed = addAvg(pAcc.speed, providerHour.outputSpeeds);
                }
                providerMetricAccByDay.set(provider, pAcc);

                for (const [modelKey, modelHour] of Object.entries(providerHour.models || {})) {
                    if (!provider.models[modelKey]) {
                        provider.models[modelKey] = {
                            modelName: modelHour.modelName,
                            estimatedInput: 0,
                            actualInput: 0,
                            cacheTokens: 0,
                            outputTokens: 0,
                            requests: 0
                        };
                    }

                    const model = provider.models[modelKey];
                    model.estimatedInput += modelHour.estimatedInput;
                    model.actualInput += modelHour.actualInput;
                    model.cacheTokens += modelHour.cacheTokens;
                    model.outputTokens += modelHour.outputTokens;
                    model.requests += modelHour.requests;

                    const mAcc = modelMetricAccByDay.get(model) ?? {};
                    if (modelHour.firstTokenLatency && modelHour.firstTokenLatency > 0) {
                        mAcc.latency = addAvg(mAcc.latency, modelHour.firstTokenLatency);
                    }
                    if (modelHour.outputSpeeds && modelHour.outputSpeeds > 0) {
                        mAcc.speed = addAvg(mAcc.speed, modelHour.outputSpeeds);
                    }
                    modelMetricAccByDay.set(model, mAcc);
                }
            }
        }

        total.outputSpeeds = getAvg(totalSpeedAcc);
        total.firstTokenLatency = getAvg(totalFirstTokenLatencyAcc);

        for (const provider of Object.values(providers)) {
            const pAcc = providerMetricAccByDay.get(provider);
            provider.firstTokenLatency = getAvg(pAcc?.latency);
            provider.outputSpeeds = getAvg(pAcc?.speed);
            for (const model of Object.values(provider.models)) {
                const mAcc = modelMetricAccByDay.get(model);
                model.firstTokenLatency = getAvg(mAcc?.latency);
                model.outputSpeeds = getAvg(mAcc?.speed);
            }
        }

        return { total, providers, hourly };
    }

    /**
     * Save daily statistics results
     * Save to: <baseDir>/usages/YYYY-MM-DD/stats.json
     * Save complete date statistics and hourly statistics (including providers)
     * @private Internal use, accessed via getDateStats
     */
    private async saveDateStats(dateStr: string, stats: TokenUsageStatsFromFile): Promise<void> {
        const filePath = this.getStatsFilePath(dateStr);

        try {
            // Write version timestamp
            stats.versionTimestamp = this.getCodeVersionTimestamp();

            // Serialize writes on target file path, then atomically replace via temporary file rename to avoid concurrent overwrites and partial JSON
            await AtomicJsonFile.runExclusive(filePath, async () => {
                await AtomicJsonFile.writeJsonAtomically(filePath, stats);
            });

            // Update index file
            await this.indexManager.updateIndex(dateStr, stats.total);

            StatusLogger.debug(
                `[LogStatsManager] Saved date statistics to stats.json: ${dateStr}, version=${new Date(stats.versionTimestamp).toISOString()}`
            );
        } catch (err) {
            StatusLogger.error(`[LogStatsManager] Failed to save date statistics: ${dateStr}`, err);
            throw err;
        }
    }

    /**
     * Check and regenerate expired statistics
     * Called when opening statistics page to ensure all dates stats.json are up to date
     * @returns Successfully regenerated date statistics, key is date string
     */
    async regenerateOutdatedStats(): Promise<Record<string, TokenUsageStatsFromFile>> {
        const startTime = Date.now();

        // Get list of all dates needing regeneration
        const outdatedDates = await this.getOutdatedDates();
        if (outdatedDates.length === 0) {
            StatusLogger.debug('[LogStatsManager] All statistics are up to date, no need to regenerate');
            return {};
        }

        StatusLogger.debug(`[LogStatsManager] Found ${outdatedDates.length} dates of statistics needing regeneration`);

        const results: Record<string, TokenUsageStatsFromFile> = {};
        for (const dateStr of outdatedDates) {
            try {
                // Recalculate statistics for this date (use getDateStats to automatically handle calculation and saving)
                const stats = await this.getDateStats(dateStr);

                // Record results
                results[dateStr] = stats;
                StatusLogger.debug(`[LogStatsManager] Regenerated statistics for date ${dateStr}`);
            } catch (err) {
                StatusLogger.warn(`[LogStatsManager] Failed to regenerate statistics for date ${dateStr}:`, err);
            }
        }

        const elapsed = Date.now() - startTime;
        StatusLogger.debug(
            `[LogStatsManager] Statistics regeneration complete: ${Object.keys(results).length}/${outdatedDates.length} successful (elapsed: ${elapsed}ms)`
        );
        return results;
    }

    /**
     * Get list of all dates needing regeneration
     * @private Internal use, accessed via regenerateOutdatedStats
     */
    private async getOutdatedDates(): Promise<string[]> {
        const outdatedDates: string[] = [];

        if (!fsSync.existsSync(this.baseDir)) {
            return outdatedDates;
        }

        try {
            // Read all date directories
            const entries = await fs.readdir(this.baseDir, { withFileTypes: true });

            for (const entry of entries) {
                if (entry.isDirectory()) {
                    const dateStr = entry.name;
                    // Check if valid date format
                    if (/^\d{4}-\d{2}-\d{2}$/.test(dateStr)) {
                        // Check if regeneration is needed
                        if (await this.needsRegeneration(dateStr)) {
                            outdatedDates.push(dateStr);
                        }
                    }
                }
            }

            return outdatedDates;
        } catch (err) {
            StatusLogger.error('[LogStatsManager] Failed to get expired dates list', err);
            return outdatedDates;
        }
    }

    // ==================== Private Helper Methods ====================

    /**
     * Get statistics file path
     */
    private getStatsFilePath(dateStr: string): string {
        return path.join(this.baseDir, dateStr, 'stats.json');
    }

    /**
     * Read date statistics from persisted file
     * Read <baseDir>/usages/YYYY-MM-DD/stats.json file
     * @param dateStr Date string (YYYY-MM-DD)
     * @returns Statistics object, returns null if not exists
     */
    private async loadStats(dateStr: string): Promise<TokenUsageStatsFromFile | null> {
        const filePath = this.getStatsFilePath(dateStr);
        if (!fsSync.existsSync(filePath)) {
            return null;
        }

        try {
            const content = await fs.readFile(filePath, 'utf-8');
            const statsData: TokenUsageStatsFromFile = JSON.parse(content);
            StatusLogger.debug(`[LogStatsManager] Read date statistics from stats.json: ${dateStr}`);
            return statsData;
        } catch (err) {
            StatusLogger.warn(`[LogStatsManager] Failed to read statistics: ${dateStr}`, err);
            return null;
        }
    }

    /**
     * Check if specified date statistics file needs regeneration
     * Judgment logic:
     * 1. If stats.json does not exist, needs generation
     * 2. If no versionTimestamp (old format cache), needs regeneration
     * 3. If versionTimestamp < code version timestamp, needs regeneration (code has been updated)
     * 4. If stats.json modification time < cache creation time, indicates old statistics generated before cache rebuild, needs regeneration
     * 5. If stats.json modification time >= cache creation time, check if there are newer log files
     * @param dateStr Date string (YYYY-MM-DD)
     * @returns true means needs regeneration, false means no need to regenerate
     */
    private async needsRegeneration(dateStr: string): Promise<boolean> {
        const statsFilePath = this.getStatsFilePath(dateStr);
        // If stats.json does not exist, needs generation
        if (!fsSync.existsSync(statsFilePath)) {
            return true;
        }

        try {
            // Read stats.json content, check versionTimestamp
            const content = await fs.readFile(statsFilePath, 'utf-8');
            const statsData: TokenUsageStatsFromFile = JSON.parse(content);

            // Check version timestamp
            const savedVersionTimestamp = statsData.versionTimestamp;
            const codeVersionTimestamp = this.getCodeVersionTimestamp();

            // Step 2: If no versionTimestamp (old format cache), needs regeneration
            if (savedVersionTimestamp === undefined) {
                StatusLogger.debug(
                    `[LogStatsManager] stats.json for date ${dateStr} needs recalculation (no version timestamp, old format cache)`
                );
                return true;
            }

            // Step 3: If cache version < code version, needs regeneration
            if (savedVersionTimestamp < codeVersionTimestamp) {
                StatusLogger.debug(
                    `[LogStatsManager] stats.json for date ${dateStr} needs recalculation (cache version: ${new Date(savedVersionTimestamp).toISOString()}, code version: ${new Date(codeVersionTimestamp).toISOString()})`
                );
                return true;
            }

            // Step 4: Check if cache is newer than log file
            const statsStats = fsSync.statSync(statsFilePath);
            const statsMtime = statsStats.mtimeMs;
            const cacheVersionTimestamp = this.getCacheVersionTimestamp();

            // If stats.json modification time < cache creation time, indicates old statistics generated before cache rebuild, needs regeneration
            if (statsMtime < cacheVersionTimestamp) {
                return true;
            }

            // stats.json modification time >= cache creation time, check if there are newer log files
            const dateFolder = path.join(this.baseDir, dateStr);
            if (!fsSync.existsSync(dateFolder)) {
                return false;
            }

            // Read all files in date folder
            const files = await fs.readdir(dateFolder);
            const logFiles = files.filter(f => f.endsWith('.jsonl'));
            // Check if any log file modification time is later than stats.json
            for (const logFile of logFiles) {
                const logFilePath = path.join(dateFolder, logFile);
                const logStats = fsSync.statSync(logFilePath);
                if (logStats.mtimeMs > statsMtime) {
                    StatusLogger.debug(
                        `[LogStatsManager] stats.json for date ${dateStr} expired (log file ${logFile} updated)`
                    );
                    return true;
                }
            }

            // No newer log files, cache is valid
            return false;
        } catch (err) {
            StatusLogger.warn(`[LogStatsManager] Failed to check if date ${dateStr} needs update:`, err);
            return false;
        }
    }

    /**
     * Ensure directory exists (create recursively)
     */
    private async ensureDirectoryExists(dirPath: string): Promise<void> {
        try {
            // Synchronous check to avoid race condition
            if (!fsSync.existsSync(dirPath)) {
                await fs.mkdir(dirPath, { recursive: true });
                StatusLogger.debug(`[LogStatsManager] Created directory: ${dirPath}`);
            }
        } catch (err) {
            // Ignore already exists error
            const error = err as NodeJS.ErrnoException;
            if (error.code !== 'EEXIST') {
                throw err;
            }
        }
    }
}
